export default {
  login: "JOEMN96",
  id: 56827756,
  node_id: "MDQ6VXNlcjU2ODI3NzU2",
  avatar_url: "https://avatars1.githubusercontent.com/u/56827756?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/JOEMN96",
  html_url: "https://github.com/JOEMN96",
  followers_url: "https://api.github.com/users/JOEMN96/followers",
  following_url: "https://api.github.com/users/JOEMN96/following{/other_user}",
  gists_url: "https://api.github.com/users/JOEMN96/gists{/gist_id}",
  starred_url: "https://api.github.com/users/JOEMN96/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/JOEMN96/subscriptions",
  organizations_url: "https://api.github.com/users/JOEMN96/orgs",
  repos_url: "https://api.github.com/users/JOEMN96/repos",
  events_url: "https://api.github.com/users/JOEMN96/events{/privacy}",
  received_events_url: "https://api.github.com/users/JOEMN96/received_events",
  type: "User",
  site_admin: false,
  name: "JOE MON",
  company: "voxforem Technologies",
  blog: "http://joemn.tk/",
  location: "kanyakumari.Tamil Nadu,India",
  email: null,
  hireable: null,
  bio: "hello There !",
  twitter_username: "aruljoe37",
  public_repos: 6,
  public_gists: 0,
  followers: 4,
  following: 5,
  created_at: "2019-10-21T11:35:57Z",
  updated_at: "2020-10-15T16:16:30Z",
};
